### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by Ir0n42** [AlfredoRamos/phpbb-ext-imgur#1]
Good morning, I have problem, when I want enter my app PIN I have this message : 
"Request for access token failed: cURL error 60: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

How can I fix this?
Thank you for your support

**Comment by AlfredoRamos** [comment]
Hi,

The certificate seems to be invalid. In general, it could be because it expired, does not match the server's name or is a self-signed certificate, wich means that it has not been validated by a certification authority.

First check that your server's datetime is correct, fixing that could fix your issue too, because it is used to check certificates expiration date.

**Comment by Ir0n42** [comment]
Thank you for your answer but it's not the problem.
I have find the bug, it just php version, need to be in STABLE not LEGACY !
THX
