### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by panteror** [AlfredoRamos/phpbb-ext-imgur#4]
Hi,

here french translation for last github master download (22/11/2017) for your next release.

Thanks

[fr.zip](https://github.com/AlfredoRamos/phpbb-ext-imgur/files/1495603/fr.zip)

**Comment by AlfredoRamos** [comment]
Thanks, I just added the French translation with small fixes.

For future references, please use a [right single quotation mark](https://unicode.org/cldr/utility/character.jsp?a=2019) `’` (`&rsquo;`, `U+2019`) instead of an escaped [apostrophe](https://unicode.org/cldr/utility/character.jsp?a=0027) `'` (`&apos;`, `U+0027`), they look almost the same, however using the last one could be the cause of denial by the extension validation team.

**Comment by panteror** [comment]
ok thanks
