### ISSUE TITLE
Settings problem with last master

### ISSUE THREAD

**Issue by panteror** [AlfredoRamos/phpbb-ext-imgur#5]
Hi,

I downloaded this morning the last master to test thumbail and to do the french translation.

On my test forum, i have error when i go to the extension settings ? normal as you are currently working on it ?

here the message : 

Fatal error: Class 'Imgur\Client' not found in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\dowfr\cache\production\container_dbdbe80dc7030ae9bd39ee30cca82130.php on line 435

I have of course clean cache before.

Thanks

**Comment by AlfredoRamos** [comment]
Hi,

The repository is for development only, it does not include the library required to upload the images, you can install them with `composer` as stated in the [Installation](https://github.com/AlfredoRamos/phpbb-ext-imgur#installation) section in the README.md file.

If you have `composer` installed, go to `ext/alfredoramos/imgur/` and run inside the following command:

```
composer install --prefer-dist --no-dev
```

If you don't have it, I will provide a download link in the phpBB forum so you can test the translation, I'm reviewing it right now.

**Comment by panteror** [comment]
I still have the same problem with the final version
https://github.com/AlfredoRamos/phpbb-ext-imgur/releases/tag/1.1.0

**Comment by AlfredoRamos** [comment]
@panteror Because it has external dependencies, other extensions usually don't need libraries to work.

This repository is not meant to provide distribution files, just to store the code, so please don't get it from here but from the phpbb.com website.

The only thing that is missing is the `vendor` directory, it should not be included in the source, because the point of using `composer `is to get (update and delete) dependencies and generate that directory.

See https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

PS: The full package was sent for validation, just wait for it to be released.

**Comment by panteror** [comment]
Ok, i understand. I’m waiting for the phpbb package.
Thanks.
