### ISSUE TITLE
Upgrading from 1.5.1 to 1.6/1.7

### ISSUE THREAD

**Issue by roiebh** [AlfredoRamos/phpbb-ext-imgur#87]
Hello,
Firstly thank you so much for this great ext.
It works fine in my phpBB 3.3.2 system with 1.5.1.
I've try to update to a newer version but found difficulties:
Run composer install --prefer-dist --no-dev inside {PHPBB_ROOT}/ext/alfredoramos/imgur/
After a research, I understand that this step can be apply only by the host.
Is that mean that I cannot upgrade to the new versions without having composer?
(just to make it clear - when I upgraded I got a blank screen while trying to get to the ext settings on both versions 1.6, 1.7 and caches weren't the issue).

**Comment by AlfredoRamos** [comment]
Hi @roiebh,

>  Firstly thank you so much for this great ext.

Thanks for your kind words.

> I've try to update to a newer version but found difficulties:
> Run `composer install --prefer-dist --no-dev inside {PHPBB_ROOT}/ext/alfredoramos/imgur/`
> After a research, I understand that this step can be apply only by the host.

Yes, but it's only for development.

>  Is that mean that I cannot upgrade to the new versions without having composer?

No, you don't need to install or have already installed Composer if you are only upgrading. Those instructions are for development and for people that have access to the command line in their servers.

>  (just to make it clear - when I upgraded I got a blank screen while trying to get to the ext settings on both versions 1.6, 1.7 and caches weren't the issue).

If you are downloading the extension from GitHub (please, don't do that unless you know what you are doing) that's normal because it's missing the required `vendor/` directory.

That directory it's essential for this extension since that's where the libraries it uses are stored, and it's generated when running `composer install`.

Please use the already packaged versions I provide (with the `vendor/`directory included) in the following topic at phpbb.com:

https://www.phpbb.com/customise/db/extension/imgur/support/topic/198266

You must not have any problems using those files.

If the problem persist, please share the error logs here or via PM on my profile at phpBB:

https://www.phpbb.com/community/ucp.php?i=pm&mode=compose&u=1389046

**Comment by roiebh** [comment]
Worked perfectly !
The version I used is from GitHub use because the link on the ext info is to GitHub and I didn't have the other link.
Thank you again, everything work just fine :)

**Comment by AlfredoRamos** [comment]
I'm glad to read that.

I'll make adjustments to avoid confusions.
